export const INCREMENT = 'INCREMENT';
export const INCREMENT_REQ = 'INCREMENT_REQ';
export const INCREMENT_ASYNC_REQ = 'INCREMENT_ASYNC_REQ';


export const SET_AUTH = 'SET_AUTH';
export const SET_AUTH_REQ = 'SET_AUTH_REQ';

export const DECREMENT = 'DECREMENT';
export const DECREMENT_REQ = 'DECREMENT_REQ';

export const ADD = 'ADD';
export const ADD_REQ = 'ADD_REQ';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_REQ = 'ADD_TO_CART_REQ';

export const DELETE_CART = 'DELETE_CART';
export const DELETE_CART_REQ = 'DELETE_CART_REQ';

export const FETCH_START = 'FETCH_START';
export const FETCH_START_REQ = 'FETCH_START_REQ';

export const FETCH_END = 'FETCH_END';
export const FETCH_END_REQ = 'FETCH_END_REQ';

export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_ERROR_REQ = 'FETCH_ERROR_REQ';

export const FETCH_AUTH = 'FETCH_AUTH'
export const FETCH_AUTH_REQ = 'FETCH_AUTH_REQ'

export const ADD_PRODUCT_AND_AUTH = 'ADD_PRODUCT_AND_AUTH'
export const ADD_PRODUCT_AND_AUTH_REQ = 'ADD_PRODUCT_AND_AUTH_REQ'

export const DELETE_PRODUCT_AND_AUTH = 'DELETE_PRODUCT_AND_AUTH';
export const DELETE_PRODUCT_AND_AUTH_REQ = 'DELETE_PRODUCT_AND_AUTH_REQ';

export const FETCH_CART = 'FETCH_CART'
export const FETCH_CART_REQ = 'FETCH_CART_REQ'

export const ADD_TO_STORE = 'ADD_TO_STORE'
export const ADD_TO_STORE_REQ = 'ADD_TO_STORE_REQ'

export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'
export const SEARCH_PRODUCT_REQ = 'SEARCH_PRODUCT_REQ'

export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const FETCH_PRODUCT_REQ = 'FETCH_PRODUCT_REQ'

export const SORT_PRODUCT = 'SORT_PRODUCT'
export const SORT_PRODUCT_REQ = 'SORT_PRODUCT_REQ'


export const BREAD_LINK = 'BREAD_LINK'
export const BREAD_LINK_REQ = 'BREAD_LINK_REQ'


export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_REQ = 'UPDATE_PRODUCT_REQ'

export const PAGINATION_PRODUCT = 'PAGINATION_PRODUCT'
export const PAGINATION_PRODUCT_REQ = 'PAGINATION_PRODUCT_REQ'

export const STATUS_INVOICE = 'STATUS_INVOICE'
export const STATUS_INVOICE_REQ = 'STATUS_INVOICE_REQ'

export const FETCT_CHECKOUT_REQ = 'FETCT_CHECKOUT_REQ'
export const FETCT_CHECKOUT = 'FETCT_CHECKOUT'

export const FETCT_SUBMIT_REQ = 'FETCT_SUBMIT_REQ'
export const FETCT_SUBMIT = 'FETCT_SUBMIT'

